language: node_js
services:
  - docker
node_js:
  - '12'
install:
  - yarn install
script:
  - echo $DOCKER_USERNAME | md5sum -t
  - echo $DOCKER_PASSWORD | md5sum -t
  - yarn test:coverage_report
  - yarn build
  - docker build -t $TRAVIS_REPO_SLUG .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $TRAVIS_REPO_SLUG
env:
  global:
    - secure: G39S4PkWF3s3io4CGqDEk6fyCKdyLmDNaisHL/kT4HkVpqaPW5b5Q/EHzccinFOeNjic3uEfBWJQOPrKEK5zDecOB6FfoSIBPOyUkQ35lM0fU0nMkIC6a9qw+M5NQBrjb90Yb/eg06lMiUfTBVrD6/FDfHjyZiavSRT62p0mSykR8cTyrPt7o+eA9+bHJe3fRv7czpnj8EOBHtDu2CzWAIkagnkk3SH7zEJz3RrCdq/Sy/Wo63+jrPxmqd5YkhVa6RP3Lp9G8VWs+0Wc3TS+7Rc2IDqC1fsgyrq84Uw8X6JX+5nrhNdqEsHsiyPOGHTKBX4hHclKFHJZ4Meh5oZY9KfeSiia9Ka0hlo2STuasGc1htlmA47xaJjX7hIG0mbk7K5f5IAZGPqmzFrvdvMlyTYOTRxsss/k7g+okf2XzTfKFo3pbAD0j7vL27BkzN1hmCm5YfpXtGRi60Pa6ijNu2n/eisRtk79KIEQk3rhFrsZapG7C4a7SAV5IsIzmRmS13N4HNEkY7zMPnSInWbKvl+0HB3M7VIuqriQ4KNATKbH4cjR0DX0EaewJBpAZZtDQCOeHAb1L+sjf+TOtq2+D/5URYQ/S5IJ4o1OsoVT9bc2OOL/AjW4sQOdqGNjlkSfOrU/EmYFCeb44hqfSxbv8RzihQKPyxy0FEdtWExSGEw=
