language: node_js
services:
  - docker
node_js:
  - '12'
install:
  - yarn install
script:
  - echo $DOCKER_USERNAME | md5sum -t
  - echo $DOCKER_PASSWORD | md5sum -t
  - yarn test:coverage_report
  - yarn build
  - docker build -t $TRAVIS_REPO_SLUG .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $TRAVIS_REPO_SLUG
env:
  global:
    secure: r5rfa3dWC5BicBntp8LzI3hJyGDB0S/3ZlxNhjIwefePKnjU4epofmTd+74S2K8gBeKGBA1xHgo3L/MqyWG6iFMgWpkS2S2KDgn//OwhCNPozvDqdnStBgaBF2QgGg2N3/+XQy7gftcUr+sJ8VJGiF0HyzrgaAXelaqpRnAU+n0Uscjr8rfMBGpV51QdRV+4dudMO+8eK/xPONGPuD4mYjsusapbjdMIe1Y+8WAh2s1Zuhk8n5nJsP6/jfaAxCIvIeFvLZJzwP+XNwm41sxTjOQrCoVjNYLMHf9QlO3KLZCNIvqbBSTdhAFKjIi7dCxwkbsM8vtUjnlERB9luHX48A0KDJtigsPXE078e9m0ai7/7H5NCCowwQ9vpcCpaPM4f9bhYoaouB6mSfYnvLQUW6rNToMOjTJ4ljP0rDQt+SkTM/kZCM0wUJF/rZlVsBr3rTsTl+bmODUW42zt7BIcF/av/73q2y/r0tKJgfEUXYlo1gHjT3eFnmmsNb92QRULCDg3evPgsrdILgvcZjGjeDvsLnlXMrh51QfB9nhFiHmvVLINHymcEyIFVjVS7U/wSsMH1ldGptR18onyBYoql+Wp5mmDFSjrZjWCBKXGGOk6EYORnWwbJ+qnRUlaMLMg97FcGm8i0Ryw0uTh2suHetP8NOU7BcrMQk0JTUrolWs=
