language: node_js
services:
- docker
node_js:
- '12'
install:
- yarn install
script:
- yarn test:coverage_report
- yarn build
- docker build -t $TRAVIS_REPO_SLUG .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $TRAVIS_REPO_SLUG
env:
  global:
    secure: I/5ts5JCM22Z63wP9rFtAA5dMaP4tbmztMjvf5iYpZBZzQK1kvkRBoQvv2KxN0XlSrEScos96PnK5NvDnurPxqdcEEUNUEcPrN7MufwVtpS7Gtf8vrE4hb3eESVeY7FfKeWHU/9xz60cu9bcpxwrDwRdH2Gs2jd7w0ietRhdjubze8b8O8JJyuYFSU4oPBx3xpO0YqC2Uy6w/Wj73C4yqbCK5dn4ADPkOFvh46k3nzjXH+e8aj991YpPIszT1I9Hd0uoXBEcbfgC7qT1+SK6wim07u4Er0T0rl6mMZfpaVZPS1nuzEkjDUprgQPPpw0njnVoczRIOUkkzY3whAfKHKaITXQ2zN8hs/PdQyQtjJZZBxmNj5M+xE1pTtS4hknSCQtUR2e4B6kv+BTCyuTFJnC/7NHAiKCoAkjMX5EPXr567kazxxq81tQt62Ex4CKugwQNwakJRHOOuBBVdIe9dRAGkCKl4outSCKd+++vrH0Yjp23BAkouDYnexGPkI4h1Hyr+lojqf4xMR9ti1YiXy20pDwfhmcXyGCchp6i6EscpHtupAeMhHNB8lxmjqrdZZVMQCwTLAISLRAx9OG9OHxIQK+6h6Eh5kWJjuuwDNtHiTRK1jpv/1W+Madbr1vrh4bo4ERIBME7wZwZ+O11Tfcsdix/YH5EoMJtIMk9Isw=
