language: node_js
services:
  - docker
node_js:
  - '12'
install:
  - yarn install
script:
  - yarn test:coverage_report
  - yarn build
  - docker build -t $TRAVIS_REPO_SLUG .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $TRAVIS_REPO_SLUG
env:
  global:
    secure: rq7CLXQ63gClgwMMthyY3edfKgfcX77VEcvNNuNiQKiscO9GVMQqKphIfcKG1FOYzxjfsR/TXrzeyRoAfi4/UD863qP57OrcDwego05iEEkjkqRZW+Zkd/osnSP06Vnta1ZYXGqiOU6bC13LL3nd6dSSCgAiCmFCsLRaC7sRCKPg17GPqvtwY3t/aq7T2imNzwPNnaqZcVDUMPLlMnjxpae8JVG6quDeO+E0Z7S/EmVwnuG8azA4ivbTwCKKvy5bgcCqv2JVLJjfAYBEUx1yRbdH/Xj/ARzvqCE2QfOYWZl9LhypaE6uWWB9tXQe3dTZhPZYQvTf+cCk9jZHevNVxzboabMGnyhS6Xu5zuwxSXOoMnE0acWx3ugBLRvnPmgNNqbfJ+f9UWlo6ha3kiP1fgcDA3On5z6TVC0D5w2Fr4KfPbP9BTZVnSTz9o0s8Ks5JGYU2djwA1S81AkFn6rnwNHOVaT5Wbf7qF9qRVu6k6/cnpq/rNpRiCfl641C2QechdGxHYfEB2ZOnDJGWsT5kIGDfSYC/DMnx/snXjZ2bpgH573vfmC0z/3D+OJGxyvQ785xPQhEoemcFg2ZPkKDZTb8FWS9zCHjgsM8SC+tGKXU6ZhwKEYiHuWG3tuwuEnAjt5gQc4Q8Wy/QtW6u0sbMin0GKIH0YNn0X5pIyT6nmk=
